/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/model/untitled.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Bluza(props) {
  const { nodes, materials } = useGLTF("./model/untitled.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, -1.089, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group scale={100}>
            <mesh
              geometry={nodes.hoodie_Rib_2X2_468gsm_hoodie_end_0.geometry}
              material={materials["lambert1.001"]}
            />
            <mesh
              geometry={nodes.hoodie_stitches_0.geometry}
              material={materials.stitches}
            />
            <mesh
              geometry={nodes.hoodie_stitches_0001.geometry}
              material={materials.stitches}
            />
            <mesh
              geometry={nodes.hoodie_stitches_0002.geometry}
              material={materials.stitches}
            />
            <mesh
              geometry={nodes.hoodie_stitches_0003.geometry}
              material={materials.stitches}
            />
            <mesh
              geometry={nodes.hoodie_stitches_0004.geometry}
              material={materials.stitches}
            />
            <mesh
              geometry={nodes.hoodie_stitches_0005.geometry}
              material={materials.stitches}
            />
            <mesh
              geometry={nodes.hoodie_stitches_0006.geometry}
              material={materials.stitches}
            />
            <mesh
              geometry={nodes.hoodie_stitches_0007.geometry}
              material={materials.stitches}
            />
            <mesh
              geometry={nodes.hoodie_stitches_0008.geometry}
              material={materials.stitches}
            />
            <mesh
              geometry={nodes.hoodie_stitches_0009.geometry}
              material={materials.stitches}
            />
            <mesh
              geometry={nodes.hoodie_stitches_0010.geometry}
              material={materials.stitches}
            />
            <mesh
              geometry={nodes.hoodie_Sweat_hood_Rib_1X1_319gsm_hood_0.geometry}
              material={materials["lambert1.001"]}
            />
            <mesh
              geometry={nodes.hoodie_Sweat_Rib_1X1_319gsm_hoodie_0.geometry}
              material={materials["lambert1.001"]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./model/untitled.glb");
